# This workflow can be manually triggered to deploy changes to github branch.
# You can specify branches using patterns like 'feature/' or 'pulls/'.
# @read: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
name: Deploy website to github pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the start and end of an ongoing run
concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  build:
    # run only on upstream repository
    if: github.repository == 'TheVVibe/the-v-vibe-com'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the code'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branchName }}
      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: 'Install the dependencies'
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Upload artifact
        # Uploads the build output to be used by the deploy job
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment-url.outputs.url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment-url
        uses: actions/deploy-pages@v4
 